// ============================================================
// SEED DATA — Data awal untuk demo
// ============================================================
import { User, Kota } from "./types";

export const SEED_USERS: User[] = [
  {
    id: "u1",
    username: "admin",
    password: "admin123",
    name: "Administrator",
    role: "ADMIN",
    nip: "000001",
    divisi: "IT",
  },
  {
    id: "u2",
    username: "sdm01",
    password: "sdm123",
    name: "Budi Santoso",
    role: "SDM",
    nip: "100001",
    divisi: "Divisi SDM",
  },
  {
    id: "u3",
    username: "pegawai01",
    password: "pegawai123",
    name: "Andi Wijaya",
    role: "PEGAWAI",
    nip: "200001",
    divisi: "Divisi Teknik",
  },
  {
    id: "u4",
    username: "pegawai02",
    password: "pegawai123",
    name: "Siti Rahayu",
    role: "PEGAWAI",
    nip: "200002",
    divisi: "Divisi Keuangan",
  },
];

export const SEED_KOTA: Kota[] = [
  {
    id: "k1",
    nama: "Kota Bandung",
    latitude: -6.9175,
    longitude: 107.6191,
    provinsi: "Jawa Barat",
    pulau: "Jawa",
    luarNegeri: false,
  },
  {
    id: "k2",
    nama: "Kota Jakarta",
    latitude: -6.2088,
    longitude: 106.8456,
    provinsi: "DKI Jakarta",
    pulau: "Jawa",
    luarNegeri: false,
  },
  {
    id: "k3",
    nama: "Kota Surabaya",
    latitude: -7.2575,
    longitude: 112.7521,
    provinsi: "Jawa Timur",
    pulau: "Jawa",
    luarNegeri: false,
  },
  {
    id: "k4",
    nama: "Kota Yogyakarta",
    latitude: -7.7956,
    longitude: 110.3695,
    provinsi: "DI Yogyakarta",
    pulau: "Jawa",
    luarNegeri: false,
  },
  {
    id: "k5",
    nama: "Kota Semarang",
    latitude: -6.9932,
    longitude: 110.4203,
    provinsi: "Jawa Tengah",
    pulau: "Jawa",
    luarNegeri: false,
  },
  {
    id: "k6",
    nama: "Kota Medan",
    latitude: 3.5952,
    longitude: 98.6722,
    provinsi: "Sumatera Utara",
    pulau: "Sumatera",
    luarNegeri: false,
  },
  {
    id: "k7",
    nama: "Kota Makassar",
    latitude: -5.1477,
    longitude: 119.4327,
    provinsi: "Sulawesi Selatan",
    pulau: "Sulawesi",
    luarNegeri: false,
  },
  {
    id: "k8",
    nama: "Kota Denpasar",
    latitude: -8.6705,
    longitude: 115.2126,
    provinsi: "Bali",
    pulau: "Bali",
    luarNegeri: false,
  },
  {
    id: "k9",
    nama: "Kota Palembang",
    latitude: -2.9761,
    longitude: 104.7754,
    provinsi: "Sumatera Selatan",
    pulau: "Sumatera",
    luarNegeri: false,
  },
  {
    id: "k10",
    nama: "Kota Pontianak",
    latitude: -0.0263,
    longitude: 109.3425,
    provinsi: "Kalimantan Barat",
    pulau: "Kalimantan",
    luarNegeri: false,
  },
  {
    id: "k11",
    nama: "Singapura",
    latitude: 1.3521,
    longitude: 103.8198,
    provinsi: "-",
    pulau: "-",
    luarNegeri: true,
  },
  {
    id: "k12",
    nama: "Kuala Lumpur",
    latitude: 3.139,
    longitude: 101.6869,
    provinsi: "-",
    pulau: "-",
    luarNegeri: true,
  },
  {
    id: "k13",
    nama: "Kota Bogor",
    latitude: -6.5971,
    longitude: 106.806,
    provinsi: "Jawa Barat",
    pulau: "Jawa",
    luarNegeri: false,
  },
  {
    id: "k14",
    nama: "Kota Cirebon",
    latitude: -6.7063,
    longitude: 108.5571,
    provinsi: "Jawa Barat",
    pulau: "Jawa",
    luarNegeri: false,
  },
];
